name: nyc-street-flooding-analysis
channels:
  - conda-forge
  - defaults
dependencies:
  - asttokens=2.2.1
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - bzip2=1.0.8
  - ca-certificates=2022.12.7
  - certifi=2022.12.7
  - colorama=0.4.6
  - comm=0.1.2
  - debugpy=1.6.6
  - decorator=5.1.1
  - executing=1.2.0
  - importlib-metadata=6.0.0
  - importlib_metadata=6.0.0
  - ipykernel=6.21.3
  - ipython=8.11.0
  - jedi=0.18.2
  - jupyter_client=8.0.3
  - jupyter_core=5.2.0
  - libffi=3.4.2
  - libsodium=1.0.18
  - matplotlib-inline=0.1.6
  - nest-asyncio=1.5.6
  - openssl=1.1.1t
  - packaging=23.0
  - parso=0.8.3
  - pickleshare=0.7.5
  - pip=22.2.2
  - platformdirs=3.1.1
  - prompt-toolkit=3.0.38
  - prompt_toolkit=3.0.38
  - psutil=5.9.4
  - pure_eval=0.2.2
  - pygments=2.14.0
  - python=3.11.0
  - python-dateutil=2.8.2
  - python_abi=3.11
  - pywin32=304
  - pyzmq=25.0.0
  - setuptools=65.5.0
  - six=1.16.0
  - sqlite=3.40.1
  - stack_data=0.6.2
  - tk=8.6.12
  - tornado=6.2
  - traitlets=5.9.0
  - typing-extensions=4.5.0
  - typing_extensions=4.5.0
  - tzdata=2022g
  - ucrt=10.0.22621.0
  - vc=14.2
  - vs2015_runtime=14.34.31931
  - wcwidth=0.2.6
  - wheel=0.37.1
  - wincertstore=0.2
  - xz=5.2.10
  - zeromq=4.3.4
  - zipp=3.15.0
  - zlib=1.2.13
  - pip:
    - accessible-pygments==0.0.3
    - alabaster==0.7.13
    - attrs==22.2.0
    - babel==2.12.1
    - beautifulsoup4==4.11.2
    - branca==0.6.0
    - cenpy==1.0.1
    - charset-normalizer==3.1.0
    - click==8.1.3
    - click-plugins==1.1.1
    - cligj==0.7.2
    - contourpy==1.0.7
    - cycler==0.11.0
    - diagrams==0.23.3
    - docutils==0.18.1
    - fastjsonschema==2.16.3
    - fiona==1.9.1
    - folium==0.14.0
    - fonttools==4.39.0
    - fuzzywuzzy==0.18.0
    - geopandas==0.12.2
    - greenlet==2.0.2
    - htmlmin==0.1.12
    - idna==3.4
    - imagehash==4.3.1
    - imagesize==1.4.1
    - ipywidgets==8.0.4
    - jinja2==3.1.2
    - joblib==1.2.0
    - jsonschema==4.17.3
    - jupyter-book==0.15.1
    - jupyter-cache==0.5.0
    - jupyterlab-widgets==3.0.5
    - kiwisolver==1.4.4
    - latexcodec==2.0.1
    - levenshtein==0.20.9
    - libpysal==4.7.0
    - linkify-it-py==2.0.0
    - mapclassify==2.5.0
    - markdown-it-py==2.2.0
    - markupsafe==2.1.2
    - matplotlib==3.6.3
    - mdit-py-plugins==0.3.5
    - mdurl==0.1.2
    - multimethod==1.9.1
    - munch==2.5.0
    - myst-nb==0.17.1
    - myst-parser==0.18.1
    - nbclient==0.5.13
    - nbformat==5.7.3
    - networkx==3.0
    - numpy==1.23.5
    - pandas==1.5.3
    - patsy==0.5.3
    - phik==0.12.3
    - pillow==9.4.0
    - pybtex==0.24.0
    - pybtex-docutils==1.0.2
    - pydantic==1.10.6
    - pydata-sphinx-theme==0.13.1
    - pyparsing==3.0.9
    - pyproj==3.4.1
    - pyrsistent==0.19.3
    - python-dotenv==1.0.0
    - python-graphviz==0.20.1
    - pytz==2022.7.1
    - pywavelets==1.4.1
    - pyyaml==6.0
    - rapidfuzz==2.13.7
    - requests==2.28.2
    - rtree==1.0.1
    - scikit-learn==1.2.2
    - scipy==1.9.3
    - seaborn==0.12.2
    - shapely==2.0.1
    - snowballstemmer==2.2.0
    - soupsieve==2.4
    - sphinx==5.0.2
    - sphinx-book-theme==1.0.0
    - sphinx-comments==0.0.3
    - sphinx-copybutton==0.5.1
    - sphinx-design==0.3.0
    - sphinx-external-toc==0.3.1
    - sphinx-jupyterbook-latex==0.5.2
    - sphinx-multitoc-numbering==0.1.3
    - sphinx-thebe==0.2.1
    - sphinx-togglebutton==0.3.2
    - sphinxcontrib-applehelp==1.0.4
    - sphinxcontrib-bibtex==2.5.0
    - sphinxcontrib-devhelp==1.0.2
    - sphinxcontrib-htmlhelp==2.0.1
    - sphinxcontrib-jsmath==1.0.1
    - sphinxcontrib-qthelp==1.0.3
    - sphinxcontrib-serializinghtml==1.1.5
    - sqlalchemy==1.4.46
    - statsmodels==0.13.5
    - tabulate==0.9.0
    - tangled-up-in-unicode==0.2.0
    - threadpoolctl==3.1.0
    - tqdm==4.64.1
    - typed-ast==1.5.4
    - typeguard==2.13.3
    - uc-micro-py==1.0.1
    - urllib3==1.26.15
    - visions==0.7.5
    - widgetsnbextension==4.0.5
    - ydata-profiling==4.1.0
