name: nyc-street-flooding-analysis-dev01
channels:
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2023.01.10
  - certifi=2022.12.7
  - libffi=3.4.2
  - openssl=1.1.1t
  - pip=22.3.1
  - python=3.11.0
  - sqlite=3.41.1
  - tk=8.6.12
  - tzdata=2022g
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wincertstore=0.2
  - xz=5.2.10
  - zlib=1.2.13
  - pip:
    - accessible-pygments==0.0.3
    - alabaster==0.7.13
    - anyio==3.6.2
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - arrow==1.2.3
    - asttokens==2.2.1
    - attrs==22.2.0
    - babel==2.12.1
    - backcall==0.2.0
    - beautifulsoup4==4.11.2
    - bleach==6.0.0
    - branca==0.6.0
    - cenpy==1.0.1
    - cffi==1.15.1
    - charset-normalizer==3.1.0
    - click==8.1.3
    - click-plugins==1.1.1
    - cligj==0.7.2
    - colorama==0.4.6
    - comm==0.1.2
    - contourpy==1.0.7
    - cycler==0.11.0
    - debugpy==1.6.6
    - decorator==5.1.1
    - defusedxml==0.7.1
    - diagrams==0.23.3
    - docutils==0.18.1
    - executing==1.2.0
    - fastjsonschema==2.16.3
    - fiona==1.9.1
    - folium==0.14.0
    - fonttools==4.39.2
    - fqdn==1.5.1
    - fuzzywuzzy==0.18.0
    - geopandas==0.12.2
    - greenlet==2.0.2
    - htmlmin==0.1.12
    - idna==3.4
    - imagehash==4.3.1
    - imagesize==1.4.1
    - importlib-metadata==6.1.0
    - ipykernel==6.21.3
    - ipython==8.11.0
    - ipython-genutils==0.2.0
    - ipywidgets==8.0.4
    - isoduration==20.11.0
    - jedi==0.18.2
    - jinja2==3.1.2
    - joblib==1.2.0
    - jsonpointer==2.3
    - jsonschema==4.17.3
    - jupyter==1.0.0
    - jupyter-book==0.15.1
    - jupyter-cache==0.5.0
    - jupyter-client==8.0.3
    - jupyter-console==6.6.3
    - jupyter-core==5.3.0
    - jupyter-events==0.6.3
    - jupyter-server==2.5.0
    - jupyter-server-terminals==0.4.4
    - jupyterlab-pygments==0.2.2
    - jupyterlab-widgets==3.0.5
    - kiwisolver==1.4.4
    - latexcodec==2.0.1
    - levenshtein==0.20.9
    - libpysal==4.7.0
    - linkify-it-py==2.0.0
    - mapclassify==2.5.0
    - markdown-it-py==2.2.0
    - markupsafe==2.1.2
    - matplotlib==3.6.3
    - matplotlib-inline==0.1.6
    - mdit-py-plugins==0.3.5
    - mdurl==0.1.2
    - mistune==2.0.5
    - multimethod==1.9.1
    - munch==2.5.0
    - myst-nb==0.17.1
    - myst-parser==0.18.1
    - nbclassic==0.5.3
    - nbclient==0.5.13
    - nbconvert==7.2.10
    - nbformat==5.7.3
    - nest-asyncio==1.5.6
    - networkx==3.0
    - notebook==6.5.3
    - notebook-shim==0.2.2
    - numpy==1.23.5
    - packaging==23.0
    - pandas==1.5.3
    - pandocfilters==1.5.0
    - parso==0.8.3
    - patsy==0.5.3
    - phik==0.12.3
    - pickleshare==0.7.5
    - pillow==9.4.0
    - platformdirs==3.1.1
    - plotly==5.13.1
    - prometheus-client==0.16.0
    - prompt-toolkit==3.0.38
    - psutil==5.9.4
    - pure-eval==0.2.2
    - pybtex==0.24.0
    - pybtex-docutils==1.0.2
    - pycparser==2.21
    - pydantic==1.10.6
    - pydata-sphinx-theme==0.13.1
    - pygments==2.14.0
    - pyparsing==3.0.9
    - pyproj==3.4.1
    - pyrsistent==0.19.3
    - python-dateutil==2.8.2
    - python-dotenv==1.0.0
    - python-graphviz==0.20.1
    - python-json-logger==2.0.7
    - python-levenshtein==0.20.9
    - pytz==2022.7.1
    - pywavelets==1.4.1
    - pywin32==305
    - pywinpty==2.0.10
    - pyyaml==6.0
    - pyzmq==25.0.1
    - qtconsole==5.4.1
    - qtpy==2.3.0
    - rapidfuzz==2.13.7
    - requests==2.28.2
    - rfc3339-validator==0.1.4
    - rfc3986-validator==0.1.1
    - rtree==1.0.1
    - scikit-learn==1.2.2
    - scipy==1.9.3
    - seaborn==0.12.2
    - send2trash==1.8.0
    - setuptools==67.6.0
    - shapely==2.0.1
    - six==1.16.0
    - sniffio==1.3.0
    - snowballstemmer==2.2.0
    - soupsieve==2.4
    - sphinx==5.0.2
    - sphinx-book-theme==1.0.0
    - sphinx-comments==0.0.3
    - sphinx-copybutton==0.5.1
    - sphinx-design==0.3.0
    - sphinx-external-toc==0.3.1
    - sphinx-jupyterbook-latex==0.5.2
    - sphinx-multitoc-numbering==0.1.3
    - sphinx-thebe==0.2.1
    - sphinx-togglebutton==0.3.2
    - sphinxcontrib-applehelp==1.0.4
    - sphinxcontrib-bibtex==2.5.0
    - sphinxcontrib-devhelp==1.0.2
    - sphinxcontrib-htmlhelp==2.0.1
    - sphinxcontrib-jsmath==1.0.1
    - sphinxcontrib-qthelp==1.0.3
    - sphinxcontrib-serializinghtml==1.1.5
    - sqlalchemy==1.4.47
    - stack-data==0.6.2
    - statsmodels==0.13.5
    - tabulate==0.9.0
    - tangled-up-in-unicode==0.2.0
    - tenacity==8.2.2
    - terminado==0.17.1
    - threadpoolctl==3.1.0
    - tinycss2==1.2.1
    - tornado==6.2
    - tqdm==4.64.1
    - traitlets==5.9.0
    - typed-ast==1.5.4
    - typeguard==2.13.3
    - typing-extensions==4.5.0
    - uc-micro-py==1.0.1
    - uri-template==1.2.0
    - urllib3==1.26.15
    - visions==0.7.5
    - wcwidth==0.2.6
    - webcolors==1.12
    - webencodings==0.5.1
    - websocket-client==1.5.1
    - wheel==0.40.0
    - widgetsnbextension==4.0.5
    - ydata-profiling==4.1.1
    - zipp==3.15.0
