title: "<b>Going Beyond EDA</b><br>A Deeper Analysis of NYC 311 Street Flooding Complaints"
author: Ho Hsieh, Nathan Williamson, Mark Bauer, Chidi Ezeolu
copyright: "2023"
logo: "nyc-street-flooding-complaints-logo.png"
execute:
  timeout: 400
repository:
  url: https://github.com/datalifenyc/nyc-street-flooding-analysis
  path_to_book: analysis-book
  branch: main
exclude_patterns: [scrub-process-diagram.ipynb, explore-flood-pluto.ipynb]
html:
  favicon: favicon.ico
  use_repository_button: true
  use_issues_button: true
  extra_navbar: |
        <div>
            Powered by <a href="https://jupyterbook.org/">Jupyter Book</a>
            <br/>
            Informed by <a href="https://opendata.cityofnewyork.us">NYC Open Data</a>
            <br/>
            <span style="font-family:Baskerville;font-style:italic;color:Chocolate;">Driven by Curiosity!</span>
        </div>
  announcement: "GitHub Repo Publically Available - March 6!"
sphinx:
  config:
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
    bibtex_reference_style: author_year
bibtex_bibfiles:
  - references.bib
launch_buttons:
  binderhub_url: "https://mybinder.org/v2/gh/datalifenyc/nyc-street-flooding-analysis/HEAD"
  colab_url: "https://colab.research.google.com"